# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nconl.proto\"*\n\x0b\x43onLMetrics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"9\n\tConLStats\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x1d\n\x07metrics\x18\x02 \x03(\x0b\x32\x0c.ConLMetrics\"C\n\nConLParams\x12\n\n\x02op\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\x0c\x12\x19\n\x05stats\x18\x04 \x01(\x0b\x32\n.ConLStatsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONLMETRICS._serialized_start=14
  _CONLMETRICS._serialized_end=56
  _CONLSTATS._serialized_start=58
  _CONLSTATS._serialized_end=115
  _CONLPARAMS._serialized_start=117
  _CONLPARAMS._serialized_end=184
# @@protoc_insertion_point(module_scope)
